### ISSUE TITLE
Наброски сюжета

### ISSUE THREAD

**Issue by Pavyk96** [Pavyk96/game-designer#4]
**Сделать наброски сюжета**

- Главный герой
- Второстепенные персонажи
- Наброски сюжета
- Задать сеттинг игры

_Егор, юзай вот этот сайт _https://miro.com/app/dashboard/_ , чтобы показать ход мыслей, структуру и т.п_

**Comment by satonagrad1234** [comment]
https://miro.com/app/board/uXjVNVj6JM4=/
